### ISSUE TITLE
LeftSideOfBoard

### ISSUE THREAD

**Issue by MathiasCiarlo** [BorisNimai/TetrisJavaFX#4]
Lurer på om dette kanskje kan være til hjelp?

```
...
Caused by: java.lang.IndexOutOfBoundsException: Index: 36, Size: 36
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at LeftSideOfBoard.<init>(LeftSideOfBoard.java:26)
    at Tetris.start(Tetris.java:111)
...
```

En liten arrayoutofbounds på LeftSideOfBoard.java, linje 26? :)
Dette er linje 26:

``` java
if(bag.getBag().get(nextIndex).getTetrimino().get(i) != 0){
```

Hvis du tar en kikk på hvor "i" kommer fra oppdager du dette:

``` java
for(int i = 0; i <80; i++){
```

Hmm.. Hardkodet øvre grense? Det er å be om bråk ;)
Har ikke sett så nøye på koden, men jeg tror det er her problemet ligger (eventuelt varibelen "nextIndex") :)
Lykke til vidre med prosjektet :)

**Comment by HenrikJohns1** [comment]
Takk da funker det kansje å lure den #:game_die:. 
At jeg lager et nytt objekt av venstresiden hver eneste gang gameloopen looper.

Den gir meg feil når jeg prøver å lagre pekere til canvas i en arrayList.
Jeg klarer ikke å forstå hvorfor dette ikke skal fungere.

```
 for(int i = 0; i <80; i++){
        //          tempCanvas = new Canvas(10,10);
        canvasList.add(new Canvas(10,10));
        tempCanvas = canvasList.get(i);
             .......


```

```
Exception in Application start method
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at LeftSideOfBoard.<init>(LeftSideOfBoard.java:25)
        at Tetris.start(Tetris.java:111)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
        ... 1 more
```

når jeg prøver å adde pekere til canvas i en arrayliste 

```
 public LeftSideOfBoard(GridPane gp, Bag bag){
        this.gp = gp;
        Canvas tempCanvas;
        GraphicsContext tempGc;

        for(int i = 0; i <80; i++){
        //          tempCanvas = new Canvas(10,10);
        canvasList.add(new Canvas(10,10));
        tempCanvas = canvasList.get(i);

            tempGc = tempCanvas.getGraphicsContext2D();
            tempGc.setFill(Color.WHITE);
            tempGc.fillRect(1,1,9,9);

            if(i <bag.getBag().get(nextIndex).getTetrimino().size()/4
               && bag.getBag().get(nextIndex).getTetrimino().get(i) != 0){
                tempGc.setFill(Color.RED);
                tempGc.fillRect(1,1,9,9);

            }
            if(bag.getBag().get(nextIndex).getTetrimino().size()/4 == 9){
                dimention =3;
            }else{
                dimention = 4;
            }

            //gp.add(tempCanvas,i%dimention,i/dimention); 


          gcList.add(tempGc);
            //drawNextTetriminos();
        }
    }
```

**Comment by HenrikJohns1** [comment]
Tror jeg fant lønsningen på problemet.
